[project]
name = "tradepy"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cachetools>=7.1.4,<8.0.0",
    "dotenv>=0.9.9,<1.0.0",
    "fastexcel>=0.20.2,<1.0.0",
    "financetoolkit>=2.1.0",
    "loguru>=0.7.3",
    "pandera[polars]>=0.31.1,<0.40.0",
    "plotly>=6.8.0",
    "polars[pyarrow,pandas]>=1.41.1,<1.50.0",
    "pydantic>=2.13.4,<3.0.0",
    "pydash>=8.0.6",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "tenacity>=9.1.4,<10.0.0",
    "tushare>=1.4.29,<1.5.0",
    "typer>=0.26.2,<0.27.0",
]

[dependency-groups]
dev = [
    "cython>=3.2.5",
    "flameprof>=0.4",
    "ipython>=9.13.0",
    "ipywidgets>=8.1.8",
    "py-spy>=0.4.2",
    "pyinstrument>=5.1.2",
    "pyright>=1.1.409",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.14",
    "setuptools>=82.0.1",
    "ta-lib>=0.6.8",
]


[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::UserWarning",
    "ignore::FutureWarning",
]
addopts = "-v --cov=tradepy --cov-report=term"

[build-system]
requires = ["setuptools", "wheel", "cython>=3.2.5"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tradepy*"]
