FROM python:3.11

COPY . /code
WORKDIR /code

# RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/ && \
#     pip config set global.trusted-host mirrors.aliyun.com && \
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    pip install poetry && \
    poetry install --only main
