FROM ghcr.io/namoshizun/tradepy:base

COPY . /code
WORKDIR /code

# RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list && \
#     sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list && \
RUN apt update && \
    apt install -y pandoc

RUN poetry install --only=doc
